import type { RawResource } from "@/sim/types";

/**
 * The block registry.
 *
 * Ids are a `Uint8Array` wire format for the world, so they are append-only.
 * Colours live here rather than in a texture atlas: STRATA is untextured by
 * design — form, ambient occlusion and per-voxel colour jitter carry the look,
 * which keeps the whole world one draw-call-friendly vertex-coloured mesh set
 * and loads instantly with no image assets at all.
 */

export const BLOCK = {
  AIR: 0,
  BEDROCK: 1,
  DIRT: 2,
  GRASS: 3,
  STONE: 4,
  DEEPSLATE: 5,
  BASALT: 6,
  COAL_ORE: 7,
  IRON_ORE: 8,
  COPPER_ORE: 9,
  SILVER_ORE: 10,
  TITANIUM_ORE: 11,
  CRYSTAL_ORE: 12,
  VOID_ORE: 13,
  GRAVEL: 14,
  SAND: 15,

  // Construction palette — used by building models, never generated by terrain.
  STEEL: 16,
  STEEL_DARK: 17,
  PANEL: 18,
  GLASS: 19,
  LAMP: 20,
  CONCRETE: 21,
  RUST: 22,
  COPPER_PLATE: 23,
  EMBER: 24,
  CRYSTAL_BLOCK: 25,
  SCAFFOLD: 26,
  PIPE: 27,
  MARKER: 28,
} as const;

export type BlockId = (typeof BLOCK)[keyof typeof BLOCK];

export interface BlockDef {
  readonly id: BlockId;
  readonly name: string;
  /** Linear-space RGB, 0-1. Baked straight into vertex colours. */
  readonly color: readonly [number, number, number];
  /** The original sRGB hex, for UI chips that must match the block on screen. */
  readonly hex: string;
  readonly solid: boolean;
  /** Breaks light through it — glass still culls faces against itself. */
  readonly transparent: boolean;
  /** Infinity means unbreakable. Feeds `miningTimeMs`. */
  readonly hardness: number;
  /** What hand-mining this block yields, if anything. */
  readonly drop: RawResource | null;
  /** How much per-voxel colour noise to apply. Ore veins stay crisper. */
  readonly jitter: number;
  /** Self-lit blocks ignore ambient occlusion and read as light sources. */
  readonly emissive: number;
}

/**
 * sRGB -> linear.
 *
 * The renderer outputs sRGB and treats vertex colours as linear, so palette
 * values written as web hex have to be converted or every surface comes out
 * noticeably washed out and flat. Doing it once at module load costs nothing.
 */
function srgbToLinear(channel: number): number {
  return channel <= 0.04045
    ? channel / 12.92
    : Math.pow((channel + 0.055) / 1.055, 2.4);
}

function hex(value: string): readonly [number, number, number] {
  const n = parseInt(value.replace("#", ""), 16);
  return [
    srgbToLinear(((n >> 16) & 255) / 255),
    srgbToLinear(((n >> 8) & 255) / 255),
    srgbToLinear((n & 255) / 255),
  ];
}

function def(
  id: BlockId,
  name: string,
  color: string,
  options: Partial<Omit<BlockDef, "id" | "name" | "color">> = {}
): BlockDef {
  return {
    id,
    name,
    color: hex(color),
    hex: color,
    solid: true,
    transparent: false,
    hardness: 1,
    drop: null,
    jitter: 0.06,
    emissive: 0,
    ...options,
  };
}

export const BLOCKS: Record<number, BlockDef> = {
  [BLOCK.AIR]: def(BLOCK.AIR, "Air", "#000000", { solid: false, transparent: true, hardness: 0 }),

  [BLOCK.BEDROCK]: def(BLOCK.BEDROCK, "Bedrock", "#15171e", {
    hardness: Infinity,
    jitter: 0.14,
  }),
  [BLOCK.DIRT]: def(BLOCK.DIRT, "Dirt", "#6b5133", { hardness: 0.5, jitter: 0.09 }),
  [BLOCK.GRASS]: def(BLOCK.GRASS, "Scrub", "#5d7040", { hardness: 0.5, jitter: 0.1 }),
  [BLOCK.STONE]: def(BLOCK.STONE, "Stone", "#5f6673", { hardness: 1 }),
  [BLOCK.DEEPSLATE]: def(BLOCK.DEEPSLATE, "Deepslate", "#343b4a", { hardness: 1.9 }),
  [BLOCK.BASALT]: def(BLOCK.BASALT, "Basalt", "#262231", { hardness: 3.1, jitter: 0.05 }),
  [BLOCK.GRAVEL]: def(BLOCK.GRAVEL, "Gravel", "#565b66", { hardness: 0.6, jitter: 0.13 }),
  [BLOCK.SAND]: def(BLOCK.SAND, "Sand", "#9c8557", { hardness: 0.4, jitter: 0.08 }),

  [BLOCK.COAL_ORE]: def(BLOCK.COAL_ORE, "Coal Seam", "#2b3038", {
    hardness: 1.2,
    drop: "coal",
    jitter: 0.04,
  }),
  [BLOCK.IRON_ORE]: def(BLOCK.IRON_ORE, "Iron Ore", "#a4714f", {
    hardness: 1.5,
    drop: "iron",
    jitter: 0.035,
  }),
  [BLOCK.COPPER_ORE]: def(BLOCK.COPPER_ORE, "Copper Ore", "#c26138", {
    hardness: 1.5,
    drop: "copper",
    jitter: 0.035,
  }),
  [BLOCK.SILVER_ORE]: def(BLOCK.SILVER_ORE, "Silver Ore", "#b3c0d1", {
    hardness: 2.4,
    drop: "silver",
    jitter: 0.03,
  }),
  [BLOCK.TITANIUM_ORE]: def(BLOCK.TITANIUM_ORE, "Titanium Ore", "#6f96b8", {
    hardness: 3.6,
    drop: "titanium",
    jitter: 0.03,
  }),
  [BLOCK.CRYSTAL_ORE]: def(BLOCK.CRYSTAL_ORE, "Crystal Vein", "#3ec4b4", {
    hardness: 4.4,
    drop: "crystal",
    jitter: 0.02,
    emissive: 0.28,
  }),
  [BLOCK.VOID_ORE]: def(BLOCK.VOID_ORE, "Voidstone", "#9560d4", {
    hardness: 6.2,
    drop: "voidstone",
    jitter: 0.02,
    emissive: 0.42,
  }),

  [BLOCK.STEEL]: def(BLOCK.STEEL, "Steel", "#7c8794", { hardness: 2, jitter: 0.03 }),
  [BLOCK.STEEL_DARK]: def(BLOCK.STEEL_DARK, "Dark Steel", "#3f4753", { hardness: 2, jitter: 0.03 }),
  [BLOCK.PANEL]: def(BLOCK.PANEL, "Panel", "#2c3442", { hardness: 1.6, jitter: 0.025 }),
  [BLOCK.GLASS]: def(BLOCK.GLASS, "Glass", "#8fd4e8", {
    hardness: 0.8,
    transparent: true,
    jitter: 0.02,
    emissive: 0.12,
  }),
  [BLOCK.LAMP]: def(BLOCK.LAMP, "Lamp", "#ffce7a", { hardness: 0.8, emissive: 1, jitter: 0 }),
  [BLOCK.CONCRETE]: def(BLOCK.CONCRETE, "Concrete", "#6a6f78", { hardness: 1.8 }),
  [BLOCK.RUST]: def(BLOCK.RUST, "Rusted Plate", "#8a5232", { hardness: 1.7, jitter: 0.07 }),
  [BLOCK.COPPER_PLATE]: def(BLOCK.COPPER_PLATE, "Copper Plate", "#c87a48", { hardness: 1.6 }),
  [BLOCK.EMBER]: def(BLOCK.EMBER, "Ember Port", "#ff7a2e", {
    hardness: 1.5,
    emissive: 0.9,
    jitter: 0.03,
  }),
  [BLOCK.CRYSTAL_BLOCK]: def(BLOCK.CRYSTAL_BLOCK, "Focused Crystal", "#5ce6d6", {
    hardness: 2.2,
    emissive: 0.7,
    jitter: 0.02,
  }),
  [BLOCK.SCAFFOLD]: def(BLOCK.SCAFFOLD, "Scaffold", "#8d7040", { hardness: 1, jitter: 0.05 }),
  [BLOCK.PIPE]: def(BLOCK.PIPE, "Pipe", "#59616e", { hardness: 1.5, jitter: 0.03 }),
  [BLOCK.MARKER]: def(BLOCK.MARKER, "Claim Marker", "#ff9a2e", {
    hardness: Infinity,
    emissive: 0.85,
    jitter: 0,
  }),
};

/** Fast lookup tables — the mesher touches these once per face, per voxel. */
export const IS_SOLID = new Uint8Array(256);
export const IS_ORE = new Uint8Array(256);
export const IS_TRANSPARENT = new Uint8Array(256);
export const EMISSIVE = new Float32Array(256);
export const JITTER = new Float32Array(256);
export const COLOR_R = new Float32Array(256);
export const COLOR_G = new Float32Array(256);
export const COLOR_B = new Float32Array(256);

for (const block of Object.values(BLOCKS)) {
  IS_SOLID[block.id] = block.solid ? 1 : 0;
  IS_ORE[block.id] = block.drop !== null ? 1 : 0;
  IS_TRANSPARENT[block.id] = block.transparent ? 1 : 0;
  EMISSIVE[block.id] = block.emissive;
  JITTER[block.id] = block.jitter;
  COLOR_R[block.id] = block.color[0];
  COLOR_G[block.id] = block.color[1];
  COLOR_B[block.id] = block.color[2];
}

/** Every block that yields a resource — used by the scanner overlay. */
export const ORE_BLOCKS: readonly BlockId[] = [
  BLOCK.COAL_ORE,
  BLOCK.IRON_ORE,
  BLOCK.COPPER_ORE,
  BLOCK.SILVER_ORE,
  BLOCK.TITANIUM_ORE,
  BLOCK.CRYSTAL_ORE,
  BLOCK.VOID_ORE,
];

export const ORE_BY_RESOURCE: Record<RawResource, BlockId> = {
  coal: BLOCK.COAL_ORE,
  iron: BLOCK.IRON_ORE,
  copper: BLOCK.COPPER_ORE,
  silver: BLOCK.SILVER_ORE,
  titanium: BLOCK.TITANIUM_ORE,
  crystal: BLOCK.CRYSTAL_ORE,
  voidstone: BLOCK.VOID_ORE,
};

export function blockDef(id: number): BlockDef {
  return BLOCKS[id] ?? BLOCKS[BLOCK.STONE];
}

export function isOre(id: number): boolean {
  return blockDef(id).drop !== null;
}

/** Hex string for UI chips that need to match a block exactly. */
export function blockHex(id: number): string {
  return blockDef(id).hex;
}
